### ISSUE TITLE
Improve error reporting to include a few lines of context

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter#110]
Currently, we report only the token on which tree-sitter choked, an `ERROR` node. This is usually not sufficient to understand what the problem is. Instead, the error message should include a few lines before and after the problematic snippet, which itself would be highlighted (if writing to the console).

This is especially useful when triaging a large number of errors when scanning many large projects.

**Comment by aryx** [comment]
Actually you can raise one of the exception in Parse_info.ml and later semgrep will autimatically show context lines. You need to construct a Parse_info.t but there is already a function for that in parse_treesitter_helper.ml

**Comment by aryx** [comment]
related: https://github.com/returntocorp/semgrep/issues/1713 where semgrep reports just the error at the first line, because that's what it does when there's no other precise line information.
