### ISSUE TITLE
Various typescript parse errors

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter#115]
Tree-sitter-typescript errors 2020-10-01
==

Those are errors reported by scanning a collection of public
repositories, using `make stat` from `lang/typescript/`.
This is for pure typescript, not tsx.

The number indicates the number of occurrences of this kind of error.

Official typescript parser implementation: https://github.com/microsoft/TypeScript/blob/master/src/compiler/parser.ts

Definite assignment assertions `let x!`
--

12
```
let LVIEW_COMPONENT_CACHE!: Map<string|null, Array<any>>;
                         ^
node type: ERROR
children: [
  "!"
]
```

PR: https://github.com/tree-sitter/tree-sitter-typescript/pull/86 (merged)

Read-only array
--

7
```
export function parseMessage(
    messageParts: TemplateStringsArray, expressions?: readonly any[], location?: SourceLocation,
                                                               ^^^
    messagePartLocations?: (SourceLocation|undefined)[],
    expressionLocations: (SourceLocation|undefined)[] = []): ParsedMessage {
node type: ERROR
children: [
  "any"
]
```

~~This one is a bit tricky.~~
PR: https://github.com/tree-sitter/tree-sitter-typescript/pull/90 (merged)

`asserts`
--

5
```
export function assertNumber(actual: any, msg: string): asserts actual is number {
                                                                ^^^^^^
```

PR: https://github.com/tree-sitter/tree-sitter-typescript/pull/88 (merged)

`infer`
--

1
```
export type ElementOf<T> = T extends (infer E)[] ? E : T extends readonly (infer F)[] ? F : never;
                                            ^
```

Tracked at https://github.com/returntocorp/semgrep/issues/2010

`[key: keytype]: valtype`
--

2
```
    const match = XRegExp.exec(url, this.regex) as ReturnType<typeof XRegExp.exec> & { [captured: string]: string };
                                                                                        ^^^^^^^^^

node type: ERROR
children: [
  expression
  ":"
]
```

Tracked at https://github.com/returntocorp/semgrep/issues/2012

`-readonly`
--

2
```
export type Writable<T> = {
  -readonly[K in keyof T]: T[K];
  ^
};
```

Tracked at https://github.com/returntocorp/semgrep/issues/2013

Optional keys (?)
--

```
  inputs?: {[P in keyof T]?: string | [string, string]};
                          ^

node type: ERROR
children: [
  "?"
]
```

Tracked by https://github.com/returntocorp/semgrep/issues/1993

Ellipsis in types
--

2
```
export function pipeBindV(values: [any, ...any[]]): any {
                                        ^^^
node type: ERROR
children: [
  "..."
]
```

Tracked at https://github.com/returntocorp/semgrep/issues/2023

Abstract class with decorator
--

```
    it('should support forward refs in useClass when impl version is also provided', () => {
      @Injectable({providedIn: 'root', useClass: forwardRef(() => SomeProviderImpl)})
      abstract class SomeProvider {
      ^^^^^^^^
      }

node type: ERROR
children: [
  "abstract"
]
```

Tracked at https://github.com/returntocorp/semgrep/issues/2023

`keyof typeof x`
--

2
```
export interface DiagnosticMessage {
  message: string;
  kind: keyof typeof ts.DiagnosticCategory;
                     ^^
}

node type: ERROR
children: [
  identifier
]
```

Tracked by https://github.com/returntocorp/semgrep/issues/1994.

Optional tuple element
--

2
```
  it('should return correct built-in types', () => {
    const tests: Array<[BuiltinType, boolean, ts.TypeFlags?]> = [
                                                          ^

node type: ERROR
children: [
  "?"
]
```

Tracked at https://github.com/returntocorp/semgrep/issues/2024

Non-null assertion operator after array dereference
--

```
      lastDstToken.parts[0]! += token.parts[0];
                              ^
```

Tracked by https://github.com/returntocorp/semgrep/issues/2025

Labeled tuple elements
--

```
export type ValidOption = [key: string, values: string[]];
                              ^^^^^^^^
export type ValidOptions = ValidOption[];

node type: ERROR
children: [
  ":"
  "string"
]
```

Tracked at https://github.com/returntocorp/semgrep/issues/2034

`this is`
--

```
  isFromDynamicInput(this: DynamicValue<R>): this is DynamicValue<DynamicValue> {
                                             ^^^^^^^
    return this.code === DynamicValueReason.DYNAMIC_INPUT;
  }
node type: ERROR
children: [
  primary_type
  "is"
]
Source code cannot be parsed by tree-sitter.
```

Tracked by https://github.com/returntocorp/semgrep/issues/1970.

**Comment by aryx** [comment]
Excellent. Maybe we could report this list to max directly so they could fix a few of those themselves?

**Comment by mjambon** [comment]
> Maybe we could report this list to max directly so they could fix a few of those themselves?

I'm done filing tickets for each bug in both tree-sitter-typescript and semgrep. Closing this!
