### ISSUE TITLE
Why tree-sitter OCaml bindings are more complicated?

### ISSUE THREAD

**Issue by nicobao** [returntocorp/ocaml-tree-sitter#126]
Hi!

Thanks for your work. That looks amazing.
I've been reading the developer docs, and think I understand that tree-sitter C output, even wrapped with OCaml bindings, is still not idiomatically typed and most importantly doesn't reference the original grammar.js appropriately.
Am I correct?

I was wondering why this problem occurs for OCaml bindings specifically and not for the Haskell/Python or Rust bindings?
Or is there something I misunderstood?
(I was thinking of writing such bindings myself and found out your repository.)

As a side question, I know that the standard tool for parsing is ocamllex/menhir in OCaml. I was wondering whether, considering your experience, you can compare both approaches (tree sitter and menhir)?
(I know that the goal of this repo is to get a tree sitter parser usable in OCaml in order to get access to all the General Programming Language grammars that were already written for tree sitter, but I am just asking, out of curiosity in general).

I know GitHub issue is generally not the go-to place for these kind of questions, so I'd totally understand if you simply ignore/close the issue.

Cheers!

**Comment by aryx** [comment]
> Hi!
> 
> Thanks for your work. That looks amazing.
> I've been reading the developer docs, and think I understand that tree-sitter C output, even wrapped with OCaml bindings, is still not idiomatically typed and most importantly doesn't reference the original grammar.js appropriately.
> Am I correct?

Yes. With tree-sitter you just get an untyped JSON of the CST, and actually certain intermediate nodes
in the grammar are not even present in the JSON (the one where the rules start with a '_')

> 
> I was wondering why this problem occurs for OCaml bindings specifically and not for the Haskell/Python or Rust bindings?
> Or is there something I misunderstood?

Maybe the other bindings are ok to get an untyped JSON CST. People in Python do not have type anyway, so
they are happy to modify the CST as a very generic Node with string and a list of children.

> (I was thinking of writing such bindings myself and found out your repository.)
> 
> As a side question, I know that the standard tool for parsing is ocamllex/menhir in OCaml. I was wondering whether, considering your experience, you can compare both approaches (tree sitter and menhir)?

Tree-sitter is using the GLR (Generalized LR) parsing algorithm, while menhir is using LR(1) which is strictly
less powerful. The grammar of many programming languages are actually ambiguous and using an LR(1) algorithm
leads to shift/reduce or reduce/reduce conflicts that are arbitrarily resolved. GLR is actually trying all the
possible parse tree and prune the infeasible one as it goes. Read on the wikipedia page on GLR for more information.

> (I know that the goal of this repo is to get a tree sitter parser usable in OCaml in order to get access to all the General Programming Language grammars that were already written for tree sitter, but I am just asking, out of curiosity in general).
> 
> I know GitHub issue is generally not the go-to place for these kind of questions, so I'd totally understand if you simply ignore/close the issue.

It's fine 👍
Feel free to ask more questions here.

> 
> Cheers!

**Comment by nicobao** [comment]
> > Hi!
> > Thanks for your work. That looks amazing.
> > I've been reading the developer docs, and think I understand that tree-sitter C output, even wrapped with OCaml bindings, is still not idiomatically typed and most importantly doesn't reference the original grammar.js appropriately.
> > Am I correct?
> 
> Yes. With tree-sitter you just get an untyped JSON of the CST, and actually certain intermediate nodes
> in the grammar are not even present in the JSON (the one where the rules start with a '_')
>  
Hmm... about the rule not even present, I think it is presented as a feature by the tree-sitter project? Why so?
As of un-typed CST, I see... I toyed with tree-sitter, making a custom grammar, and I noticed this. I didn't have the opportunity to _use_ a grammar yet, so I somehow thought this was solved later on. Also when making the grammar, errors just appear as "ERROR" node without much explanations. I suppose some more metadata is added when actually using the grammar!?

> > I was wondering why this problem occurs for OCaml bindings specifically and not for the Haskell/Python or Rust bindings?
> > Or is there something I misunderstood?
> 
> Maybe the other bindings are ok to get an untyped JSON CST. People in Python do not have type anyway, so
> they are happy to modify the CST as a very generic Node with string and a list of children.
> 
Totally logical for Python folks, but what about Haskell's...? Our cousins love types probably even more so.
I agree that ignoring an intermediate node should be the business of the CST user, rather than a decision done at the grammar creation. Or at least the function should be possibly turned off.

I quote the tree-sitter project doc:
_"If these nodes were not hidden, they would add substantial depth and noise to the syntax tree without making it any easier to understand."_

Moreover, having static type obviously help properly parsing data.
I feel like these features should be part of tree-sitter already, don't you think? Why is that not the case already, in your opinion? 
Not ignoring '_' rules in the CST and typing output does not seem like an unreasonably difficult-to-implement feature request?

> > (I was thinking of writing such bindings myself and found out your repository.)
> > As a side question, I know that the standard tool for parsing is ocamllex/menhir in OCaml. I was wondering whether, considering your experience, you can compare both approaches (tree sitter and menhir)?
> 
> Tree-sitter is using the GLR (Generalized LR) parsing algorithm, while menhir is using LR(1) which is strictly
> less powerful. The grammar of many programming languages are actually ambiguous and using an LR(1) algorithm
> leads to shift/reduce or reduce/reduce conflicts that are arbitrarily resolved. GLR is actually trying all the
> possible parse tree and prune the infeasible one as it goes. Read on the wikipedia page on GLR for more information.
> 
Thanks :+1: 


> > (I know that the goal of this repo is to get a tree sitter parser usable in OCaml in order to get access to all the General Programming Language grammars that were already written for tree sitter, but I am just asking, out of curiosity in general).
> > I know GitHub issue is generally not the go-to place for these kind of questions, so I'd totally understand if you simply ignore/close the issue.
> 
> It's fine +1
> Feel free to ask more questions here.
> 
> > Cheers!

**Comment by mjambon** [comment]
@nicobao 
> > Maybe the other bindings are ok to get an untyped JSON CST. People in Python do not have type anyway, so they are happy to modify the CST as a very generic Node with string and a list of children.

> Totally logical for Python folks, but what about Haskell's...? Our cousins love types probably even more so.

They have the same problem. On why the Semantic project uses tree-sitter, the [Drawbacks section](https://github.com/github/semantic/blob/master/docs/why-tree-sitter.md#drawbacks) has this to say:
 
> To recover a richer structure (which you can actually use for anything specialized to a specific language), you essentially have to parse the parse tree (which is what we do with assignment).

"Parsing the parse tree" is a good description of what we do with ocaml-tree-sitter as well.

**Comment by mjambon** [comment]
@nicobao 
> Also when making the grammar, errors just appear as "ERROR" node without much explanations. I suppose some more metadata is added when actually using the grammar!?

You probably can get more details from the tree-sitter folks, but I'm familiar with these ERROR nodes so I'll share what I know. 

ERROR nodes indicate malformed input. What's great is that instead of completely failing for the whole file, the tree-sitter parser tries to recover from the syntax error. ERROR nodes are placed in a position where they can be ignored (e.g. in a list of statements specified in the grammar as `repeat($.statement)`), resulting in a valid parse tree. This is very useful for some applications, such as syntax highlighting in text editors or for syntax-aware code search like semgrep.

**Comment by nicobao** [comment]
Thank you for your replies.
Last question, and then I stop bothering you :
- can js_of_ocaml be used to run some OCaml code that rely on ocaml-tree-sitter in browser?

Tree-sitter has wasm bindings accessible directly in JS. But ideally sharing code that uses tree-sitter between backend in OCaml and frontend whenever necessary would be ideal...

However I don't know if it's possible to make a build such that the C code embedded in OCaml can run as wasm while the rest of the code is transpiled to JS using js_of_ocaml?

**Comment by aryx** [comment]
I recently managed to compile most of semgrep to JS, but without the treesitter parsers indeed because it is currently C code. I did not try the wasm bindings but good to know!

**Comment by nicobao** [comment]
Thanks all for the interesting discussion!
