### ISSUE TITLE
Segfaults with newer tree-sitter versions >= 0.19.0

### ISSUE THREAD

**Issue by eatkins** [returntocorp/ocaml-tree-sitter#173]
If I update the tree-sitter library version to anything above 0.19.0 and run
```
./scripts/install_tree_sitter_lib
make test
```
the tests will terminate with a segfault:
```
ln -sf ocaml-src/_build/install/default/bin/parse-seq
/Library/Developer/CommandLineTools/usr/bin/make parse-examples
$SRC_HOME/ocaml-tree-sitter/scripts/parse-examples seq
$SRC_HOME/ocaml-tree-sitter/scripts/parse-examples: line 29: 72507 Segmentation fault: 11  "$parser" "$src" 2>&1
     72508 Done                    | tee "$cst"
make[4]: *** [parse-examples] Error 139
make[3]: *** [test] Error 2
make[2]: *** [test] Error 2
make[1]: *** [e2e] Error 2
make: *** [test] Error 2
```

**Comment by eatkins** [comment]
I only tested this on macos.

**Comment by aryx** [comment]
I also had a segfault a few months ago when we reorganized the structure of ocaml-tree-sitter. I think the issue
is that one version of tree-sitter was installed but ocaml-tree-sitter was still using an old treesitter.h corresponding to a previous version. Did you remember what was the fix @mjambon ? I think if you do 'make setup' from semgrep/, it should now do the right thing.

**Comment by eatkins** [comment]
That definitely makes sense.

**Comment by aryx** [comment]
We need to fix that because I also need 0.19.3 for recent tree-sitter-java which uses some unicode regexps
only available in 0.19.3

**Comment by aryx** [comment]
see also https://github.com/returntocorp/ocaml-tree-sitter/issues/186

**Comment by mjambon** [comment]
It probably has to do with the old libtree-sitter.so being found at linking time (the one installed globally) while the code was generated for a more recent version.
