### ISSUE TITLE
Simplify-grammar dont stop

### ISSUE THREAD

**Issue by joseeMDS** [returntocorp/ocaml-tree-sitter#178]
I am trying to use ocaml-tree-sitter with ocaml, i did the following steps:

```bash
tree-sitter generate
ocaml-tree-sitter ocaml src/grammar.json
```
and i got `Error: Aliases are not suported`
I found the simplify-grammar command and tried it at the `grammar.json` folder but has passed 5 hours and there is no results, is this the supposed behavior?

**Comment by joseeMDS** [comment]
Thanks to @anmonteiro that showed me how to do it, i didnt know that `simplify-grammar` was expecting receive something from stdin, tried: `cat grammar.json | simplify-grammar` and worked

**Comment by ievans** [comment]
Ah glad you got some help @joseeMDS !

Sorry if docs were unclear, would happily accept a pr if you or @mjambon have a clarification in mind!

**Comment by joseeMDS** [comment]
I would be happy contributing, i will open a PR adding some docs ASAP

**Comment by mjambon** [comment]
@joseeMDS we have some docs in https://github.com/returntocorp/ocaml-tree-sitter/tree/master/doc. In particular, [Code generation pipeline](https://github.com/returntocorp/ocaml-tree-sitter/blob/master/doc/code-generation-pipeline.md) explains a bit what's going on.

We're not using the tree-sitter-ocaml grammar in semgrep at this point, but we could add it to `/lang` in ocaml-tree-sitter anyway. There's a script for this, which hopefully will work (see instructions in [How to add support for a new language](https://github.com/returntocorp/ocaml-tree-sitter/blob/master/doc/adding-a-language.md)). Then the generated code would be published to its own repo, which could be plugged into an ocaml project as a git submodule [like we do in semgrep](https://github.com/returntocorp/semgrep/tree/develop/semgrep-core/src/tree-sitter-lang).

This complicated setup is designed to accommodate grammar extensions used in semgrep patterns, such as `...`. If we don't do anything, then it will be identical to the original tree-sitter-ocaml grammar. Let me see if I can set this up, it will be useful to us as well.

**Comment by mjambon** [comment]
I just added ocaml to the list of tree-sitter languages in ocaml-tree-sitter. The generated code is at https://github.com/returntocorp/semgrep-ocaml. This should build without difficulties if you add this folder into an existing dune project.
