### ISSUE TITLE
ocaml-tree-sitter does not generate bindings.c

### ISSUE THREAD

**Issue by joseeMDS** [returntocorp/ocaml-tree-sitter#179]
I used `ocaml-tree-sitter ocaml grammar.json` and generated all the ocaml files, but when i tried to build with dune i got `reference not found for octs_create_parser_ocaml"`, after some search i found at [semgrep-ruby repo](https://github.com/returntocorp/semgrep-ruby) that it should also generate a file named bindings.c, maybe i skipped some step?

**Comment by mjambon** [comment]
Yes, `bindings.c` is "generated" from a template that simply inserts the name of the target language. See the script `/scripts/gen-ocaml`. You'll see the result in https://github.com/returntocorp/semgrep-ocaml.

**Comment by mjambon** [comment]
Note that we haven't made efforts to make ocaml-tree-sitter usable outside of semgrep. For now you may have to reimplement partially some of the scripts such as `gen-c` and `gen-ocaml`.

**Comment by joseeMDS** [comment]
Hi @mjambon, thanks for the clarification and the example, the goal is to change the usage of a web-assembly file into an ocaml executable in [melange](https://github.com/melange-re/melange/tree/fork/ocaml-tree). We are using the lib with [esy-tree-sitter](https://github.com/joseeMDS/esy-tree-sitter)  and a resolution to `ocaml-tree-sitter`.

I would be happy in contributing to add `ocaml-tree-sitter` to opam

**Comment by mjambon** [comment]
@joseeMDS we'd love to have ocaml-tree-sitter in opam, go for it. I created issue #181 for discussing this.
