### ISSUE TITLE
upgrade to 0.19.3

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter#186]
We need 0.19.3 for recent tree-sitter-java:
https://github.com/tree-sitter/tree-sitter-java/commit/bd6186c24d5eb13b4623efac9d944dcc095c0dad

I tried to modify the package.json and scripts/install-tree-sitter-lib/ but got in some compilation errors.
Actually, even after reverting those changes I have compilation errors on master on my machine.

**Comment by mjambon** [comment]
I can handle this. Had to deal with it yesterday. One issue is that `tree-sitter generate` creates a `package.json` file if there isn't one already but it creates problems.
