### ISSUE TITLE
Generate automatically a parser of JSON CST produced by tree-sitter from grammar.json v0

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter#34]
Just a ticket to track martin's work.

See the quip doc for the milestones for now.

**Comment by nbrahms** [comment]
@aryx can you link the quip doc here?

**Comment by aryx** [comment]
sure, https://returntocorp.quip.com/mDY9AmeBhEQL/Tree-sitter-integration-into-pfff

**Comment by mjambon** [comment]
The parser generator for basic grammars (e.g. `arithmetic`) work! I'm expecting a few issues with larger real-world grammars. Marking v0 as done.

**Comment by nbrahms** [comment]
@mjambon Can you link to the PR that closes this?
