### ISSUE TITLE
multiple definitions of finalize_parser

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter#68]
when using both the ruby and java parser in ocaml-tree-sitter-lang, I get a compilation error because of finalized_parser
defined multiple times:
ocaml-tree-sitter-lang/ruby/lib/libtree_sitter_ruby_stubs.a(bindings.o): In function `finalize_parser':
/home/pad/github/semgrep/semgrep-core/_build/default/ocaml-tree-sitter-lang/ruby/lib/bindings.c:26: multiple definition of `finalize_parser'
ocaml-tree-sitter-lang/java/lib/libtree_sitter_java_stubs.a(bindings.o):/home/pad/github/semgrep/semgrep-core/_build/default/ocaml-tree-sitter-lang/java/lib/bindings.c:26: first defined here
collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1

Here is the definition:
void finalize_parser(value v) {
  parser_W *p;
  p = (parser_W *)Data_custom_val(v);
  ts_parser_delete(p->parser);
}

a simple 'static' in front of void finalize_parser does the trick.
The code generator for bindings.c needs to add this 'static'.

**Comment by mjambon** [comment]
oh, great, thank you. I'll do that. I may have to think of a way to test this before it reaches semgrep.
