### ISSUE TITLE
Factor out duplicate grammar nodes (needed for typescript support)

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter#69]
For typescript in particular, we see inline polymorphic variants that appear in multiple rules. Identifying these duplicates can be automated, which would save time to the programmer by generating a smaller `Boilerplate.ml` (and a smaller `CST.ml`).

For example, this `Choice_decl of [...]` appears a bunch of times:

* https://github.com/returntocorp/ocaml-tree-sitter-lang/blob/94c0b667f87dc9fa662c7e3e46d967d03437ef41/typescript/lib/CST.ml#L139-L161
* https://github.com/returntocorp/ocaml-tree-sitter-lang/blob/94c0b667f87dc9fa662c7e3e46d967d03437ef41/typescript/lib/CST.ml#L620-L642
* https://github.com/returntocorp/ocaml-tree-sitter-lang/blob/94c0b667f87dc9fa662c7e3e46d967d03437ef41/typescript/lib/CST.ml#L758-L780
* https://github.com/returntocorp/ocaml-tree-sitter-lang/blob/94c0b667f87dc9fa662c7e3e46d967d03437ef41/typescript/lib/CST.ml#L902-L924
...

**Comment by mjambon** [comment]
This could be implemented in `simplify-grammar`, by identifying duplicate nodes of some minimum "size" and creating a named rule for them.

**Comment by aryx** [comment]
Same for Java, where in Boilerplate.ml I had many times:
      | `Void_type tok -> token env tok (* "void" *)
      | `Inte_type x -> integral_type env x
      | `Floa_point_type x -> floating_point_type env x
      | `Bool_type tok -> token env tok (* "boolean" *)
      | `Id tok -> token env tok (* pattern [a-zA-Z_]\w* *)
      | `Scop_type_id x -> scoped_type_identifier env x
      | `Gene_type x -> generic_type env x


I factorize myself, but it's hard to know if you can, whether the cases are actually equal, so yes, would be nice
to remove duplicate and introduce intermediate function in Boilerplate.ml (and also intermediate types in CST.ml)

**Comment by aryx** [comment]
Same for Java with:
          | `Id tok -> token env tok (* pattern [a-zA-Z_]\w* *)
          | `Choice_open x ->
              (match x with
              | `Open tok -> token env tok (* "open" *)
              | `Modu tok -> token env tok (* "module" *)
              )
          | `Scop_id x -> scoped_identifier env x

duplicated many times.

**Comment by mjambon** [comment]
This is implemented and merged but I should add some documentation because it's complicated, as noted by @aryx  https://github.com/returntocorp/ocaml-tree-sitter/pull/80#pullrequestreview-455270883

**Comment by aryx** [comment]
I think the doc is good now.
