### ISSUE TITLE
warning 42 on Parse.ml

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter#72]
File "ocaml-tree-sitter-lang/typescript/lib/Parse.ml", line 11275, characters 30-33:
11275 |                             | Alt (0, v) ->
                                      ^^^
Warning 42: this use of Alt relies on type-directed disambiguation,
it will not compile with OCaml 4.00 or earlier.

**Comment by aryx** [comment]
Either add the qualifier, or right open, or add the @@warning "-42"?

**Comment by mjambon** [comment]
thanks for the report. working on it.
