### ISSUE TITLE
Automate parsing stats

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter#86]
Gathering the source for 10 large projects per language and parsing them takes a while. Doing this for every language that we support has become too long.

I'd like to set up a weekly job that produces parsing stats for each language and puts them where they can be consulted. Artifacts we want for each language:

* Summary: success rate (per line of code), number of files and number of lines processed. Allows us to claim we have a parsing success of approximately X% for such language.
* Stats per project, one per row in a CSV file. Allows us to see if the errors are concentrated in specific projects.
* Path or URL of each file that failed. Allows us to triage errors and create bug reports.

**Comment by aryx** [comment]
sounds great
maybe it could produce a report.html in addition to the .cvs files.

**Comment by mjambon** [comment]
Minimum functionality is done. The rest can be improved later. Closing!
