### ISSUE TITLE
Resolve type aliases

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter#91]
@aryx  wrote:

found some errors in the inline/deinline process I think for C sharp:

```
and interpolation_alignment_clause = (Token.t (* "," *) * constant_pattern)
```

It should not be constant_pattern; it should be expression. The grammar contains:

```
     constant_pattern: $ => prec.right($._expression),
```

and

```
     _pattern: $ => choice(
      $.constant_pattern,
      $.declaration_pattern,
      $.discard,
//      $.recursive_pattern,
      $.var_pattern
    ),
```

and for some reasons at a few places where there is an expression, in CST.ml there's a constant_pattern instead.

**Comment by nbrahms** [comment]
Closing as stale
